### ISSUE TITLE
GhostCell::from_slice_of_cells

### ISSUE THREAD

**Issue by 197g** [matthieu-m/ghost-cell#29]
Is it sound to have an inverse of `GhostCell::as_slice_of_cells`?

The layout is already transparent. Having such a method enables the implementation of a variant of `slice::array_windows` where exclusivity of access to the windows is guarded by a `GhostToken`.

<details>
<summary>Implementation sketch</summary>

```rust
use core::slice::Windows;
use ghost_cell::GhostCell;

pub struct GhostWindows<'brand, 'lt, T> {
    windows: Windows<'lt, GhostCell<'brand, T>>,
}

impl<'brand, 'lt, T> GhostWindows<'brand, 'lt, T> {
    pub fn new(slice: &'lt mut [T], len: usize) -> Self {
        GhostWindows {
            windows: GhostCell::from_mut(slice)
                .as_slice_of_cells()
                .windows(len),
        }
    }
}

impl<'brand, 'lt, T> Iterator for GhostWindows<'brand, 'lt, T> {
    type Item = &'lt GhostCell<'brand, [T]>;

    fn next(&mut self) -> Option<Self::Item> {
        let window: &'lt [GhostCell<'brand, T>] = self.windows.next()?;
        // SAFETY: is this sound? This is the inverse of GhostCell::as_slice_of_cells above.
        let window = unsafe { &*(window as *const _ as *const GhostCell<'brand, [T]>) };
        Some(window)
    }
}
```

</details>

**Comment by matthieu-m** [comment]
It's not _quite_ clear in your description, so I feel I better ask for clarifications.

It seems that the goal of your proposal, here, is to get mutable access to _multiple_ adjacent cells simultaneously, isn't it?

If so it's already possible today:

 - Use `GhostCell::as_slice_of_cells` to get a slice of cells.
 - Use `slice::windows` to get an iterator over windows.
 - Use `<&[GhostCell] as GhostBorrowMut>::borrow_mut` to mutably borrow all cells of the window at once.

If I misunderstood the goal, or appeal, please clarify :)

**Comment by 197g** [comment]
Indeed, I had overlooked that last step.

The feature description necessary for `GhostBorrowMut` definitely scares me away from it. Additionally, ergonomics for this are quite a lot worse. The `Iterator` would then return `&'lt [GhostCell<'brand, T>]`,or a wrapper type if we want to hide away the necessary result unwrapping on use of `GhostBorrowMut`. This no longer mirrors the intended `slice::windows_mut` well and is quite unexpected.

This leaves me still curious about the possibility of re-wrapping `& [GhostCell<T>]` into `&GhostCell<[T]>`. Is this any less sound than `GhostBorrowMut`?

**Comment by matthieu-m** [comment]
Yes, the fact that the never type is not yet stable makes it less ergonomic.

I think converting from `&'a [GhostCell<'brand, T>]` to `&'a GhostCell<'brand, [T]>` should be perfectly sound, as the elements of a slice are necessarily non-overlapping in the first place.

I'm guessing there's two potential APIs for this:

```rust
GhostCell<'brand, [T]>::from_slice[_of_cells](slice: &'a [GhostCell<'brand T>]) -> &'a Self;

// or

[GhostCell<'brand, T>]::as_cell_of_slice(&'a self) -> &'a GhostCell<'brand, [T]>;
```

I think the latter (taking self) would be more "fluent":

```rust
cell.as_slice_of_cells().windows(n).map(|w| w.as_cell_of_slice())
```

Thoughts?

**Comment by 197g** [comment]
Unfortunately the API can't reference `std::cell::Cell` since it lacks the same method.

I agree with the "fluent" style, too. This would more clearly reflect the inverse nature of the method, that the slice layout transposes across GhostCell.

Are there any consistency problems with similar methods, that is for other type constructors tranposing in this manner that would be introduced at some point? The immediate though would be `arrays` where the unstable `std` implementation simply uses a naming scheme to disambiguate. I see no reason this wouldn't work here for the inverses either. Similar if ever a transposition for tuples is desired—the inverse is unique afterall. Transposing of transparent wrappers is less clear to me, both the implementation choice and whether it should be considered here. It's not very common in other cell interfaces so probably does not enjoy much use. (And as demonstrated in the API snipped of the first comment, an `unsafe` workaround is always workable).

All in all:

```
[GhostCell<'brand, T>]::as_cell_of_slice(&'a self)  -> &'a GhostCell<'brand, [T]>;
```

**Comment by matthieu-m** [comment]
I think transposition in general is fine, since in all cases (slices, arrays, structs, tuples) the various fields/elements are non-overlapping by construction.

Abstracting over structs is about impossible right now, and abstracting over tuples is limited in arity given the lack of variadics, but abstracting over arrays should be a non-issue. Well, beyond naming of course :)

I would welcome PRs for both the slice "reverse", and PRs for arrays & tuples (up to 12 elements I guess), preferably separately.

**Comment by matthieu-m** [comment]
I went ahead and add the transposition for arrays and tuples (0-12) while I was merging your request.
