### ISSUE TITLE
maybe add a single RwLock<GhostToken <'static>> for closure haters

### ISSUE THREAD

**Issue by jonleivent** [matthieu-m/ghost-cell#34]
There are some alternatives to ghost_cell that are partially based on the criticism that ghost_cell requires all usage to be within a closure.  Can there be a single static `RwLock<GhostToken<'static>>` that would enable usage without closures?

**Comment by matthieu-m** [comment]
The goal of `GhostCell` was to demonstrate that a sound zero (runtime) overhead solution is possible -- indeed, `GhostCell` is first and foremost an academic paper demonstrating the soundness of the construct.

There are many variants of cells, starting with `Cell` and `RefCell` in the standard library, and following with an extensive ecosystem.

In particular, the [`singleton-cell` (SCell) crate](https://crates.io/crates/singleton-cell) seems to fill exactly this usecase.

I see no reason to try and compete with `SCell` in this case:

- It would result in duplicated maintenance.
- It would water down the value proposition of `GhostCell`: that it is formally proven.
